### ISSUE TITLE
run without CUDA?

### ISSUE THREAD

**Issue by m3m3-chan** [ChiFang/FaceAnalyzing#2]
Hi, 
can we run the code without using CUDA?

thanks,

**Comment by ChiFang** [comment]
hi @m3m3-chan  

thanks for your comment, this repo is out of date.
if you want to run the code without using CUDA, there are two options (according to my experience):
1. use opencv [dnn ](https://docs.opencv.org/3.4/d2/d58/tutorial_table_of_content_dnn.html)to load the caffe model in this repo to inference, like this [example](https://github.com/ChiFang/TensorFlow_XO_example/blob/master/TestPB.py)
2. use [openvino](https://software.intel.com/en-us/openvino-toolkit) SDK to convert to .bin and .xml to inference on intel CPU

**Comment by m3m3-chan** [comment]
thanks for the response. Will try that and see!
